### PR TITLE
App size

### LINKED ISSUE #142: Ledger Nano S screen showing incorrect address (40 instead of 41 characters)
A user contacted me earlier and I understood the problem as a difference in the address displayed between the wallet on the desktop and on the screen of the Ledger. We used the explorer.stacks.co view of the address to determine the correct address. 

In this image a Ledger Nano S Plus is used and the issue is not reproduced. It is added to illustrate the issue: (A) Desktop address is shown alright, (B) is not but only on a Ledger Nano S. (C) instead of the last digit the 34th digit seemed to be missing for the user using a "Nano Ledger S". 
image

The user has a "Nano Ledger S" device on which the address is split over two screens
Screen 1 shows: SPXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX (33 characters, missing 5 at the end)
Screen 2 shows: 1234567 (7 characters)

A total of 40 characters shown

Address shown on the Desktop wallet: 
SPXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX**5**1234567

A total of 41 characters shown (the correct address as also shown in the explorer for the user)

For clarification only the ledger device is showing an incorrect address omitting the 5 in this example (or 34th character)

I do not have the same device to check if I can reproduce this. It is possible this only occurs when a 41 character address is used, if you want to try and reproduce this yourself. 

Desktop Wallet version used 4.6.1
Stacks Ledger Live app version: 0.23.3

Issue on Stacks repo: https://github.com/hirosystems/stacks-wallet/issues/1147

:link: [zboto Link](https://app.clickup.com/t/86772bp3w)

### PR DESCRIPTION
**Pull request by neithanmo**
This PR aims to reduce the app size, applying some techniques that were used with another Rust app(AVAX):
- optimize for size using "z" flag.
- Remove Debug symbols.
- Avoid panicking replacing as much indexing as possible, with get(), get_mut variants.
- Update zxlib to the latest version which includes checks for character sizes in nanos, this fixes #142 

:link: [zboto Link](https://app.clickup.com/t/8677ckr92)

### CODE REVIEW

File: app/rust/src/parser/c32.rs [hunk 1]
```diff
@@ -64,55 +66,75 @@ fn double_sha256_checksum(data: &mut [u8; SHA256_LEN]) {
 fn double_sha256_checksum(data: &mut [u8; SHA256_LEN]) {
     let mut output = [0u8; SHA256_LEN];
     // safe to unwrap as we are passing the right len
-    sha256(&data[..21], &mut output[..]).unwrap();
-    data.copy_from_slice(output.as_ref());
+    sha256(&data[..21], &mut output[..]).apdu_unwrap();
+    data.iter_mut()
```
Comment (becominginsane) [inline app/rust/src/parser/c32.rs:70]: Is this really better ? I doubt there's a panic in there considering both slice references come from arrays, BUT if it's still there how about `(data.len() != output.len()).then_some(()).apdu_unwrap();`? (there are nicer/longer alternatives, like an explicit if with unreachable_unchecked inside)

File: app/rust/src/parser/c32.rs [hunk 2]
```diff
@@ -64,55 +66,75 @@ fn double_sha256_checksum(data: &mut [u8; SHA256_LEN]) {
...
+        .zip(output.as_ref().iter())
+        .for_each(|(d, o)| *d = *o);
     // safe to unwrap as we are passing the right len
-    sha256(&data[..], &mut output).unwrap();
-    data[20..24].copy_from_slice(&output[..4])
+    sha256(&data[..], &mut output).apdu_unwrap();
+    if let Some(d) = data.get_mut(20..24) {
```
Comment (becominginsane) [inline app/rust/src/parser/c32.rs:75]: I think this may actually make 2 branches still, since in the `None` case then nothing is to be done...
`.get_mut(20..24).apdu_unwrap()` is what you need I think... 

As for the length check of copy_from_slice... I think it should be okay, but I'm way less confident compared to the above, so maybe it's better to help the compiler here

File: app/rust/src/parser/message.rs [hunk 3]
```diff
@@ -118,7 +118,11 @@ impl<'a> ByteString<'a> {
         });
 
         let mut copy_len = if self.0.len() > MAX_ASCII_LEN {
-            msg[MAX_ASCII_LEN..MAX_ASCII_LEN + suffix.len()].copy_from_slice(&suffix[..]);
+            if let Some(m) = msg.get_mut(MAX_ASCII_LEN..MAX_ASCII_LEN + suffix.len()) {
```
Comment (becominginsane) [inline app/rust/src/parser/message.rs:121]: `.get_mut(xyz).ok_or(ParserError::xyz)?`

Here the compiler may be smart enough to see that the slice was just `suffix.len()` in length, so the panic should be avoidable... would add a check

File: app/rust/src/parser/spending_condition.rs [hunk 4]
```diff
@@ -389,7 +396,14 @@ impl<'a> TransactionSpendingCondition<'a> {
             // append the signatures count at the end
             if let Some(count) = self.required_signatures() {
                 buf[20..STANDARD_MULTISIG_AUTH_LEN].copy_from_slice(&count.to_be_bytes());
-                return Ok(STANDARD_MULTISIG_AUTH_LEN);
+                if let Some(b) = buf.get_mut(20..STANDARD_MULTISIG_AUTH_LEN) {
```
Comment (becominginsane) [inline app/rust/src/parser/spending_condition.rs:399]: I think here you forgot to remove the line above... anyways, same as with the others, prefer `.apdu_unwrap` instead of if let so a branch can be removed entirely (well unless you aren't sure it's gonna fit! but you checked that already)... and then copy_from_slice + length check

Also consider using [fill](https://doc.rust-lang.org/std/primitive.slice.html#method.fill) for the fills above (so it becomes roughly `buf[..xyz].fill(0)`, which is much nicer).

File: app/rust/src/parser/structured_msg.rs [hunk 5]
```diff
@@ -74,7 +75,14 @@ impl<'a> Domain<'a> {
         let mut buff = [0; 39];
 
         if let Some((key, value)) = self.tuple().iter().nth(display_idx as usize) {
-            out_key[0..key.name().len()].copy_from_slice(key.name());
+            if let Some(m) = out_key.get_mut(0..key.name().len()) {
```
Comment (becominginsane) [inline app/rust/src/parser/structured_msg.rs:78]: same as above, .ok_or(err)? and copy_from_slice should be good, no need to check lengths

File: app/rust/src/parser/transaction_payload.rs [hunk 6]
```diff
@@ -64,27 +66,39 @@ impl<'a> StxTokenTransfer<'a> {
...
+        // safe to unwrap as parser checked for proper len
+        self.0.get(at..).apdu_unwrap()
     }
 
     pub fn amount(&self) -> Result<u64, ParserError> {
         let at = self.0.len() - 34 - 8;
-        be_u64::<'a, ParserError>(&self.0[at..])
-            .map(|res| res.1)
-            .map_err(|_| ParserError::parser_unexpected_buffer_end)
+        if let Some(amount) = self.0.get(at..) {
```
Comment (becominginsane) [inline app/rust/src/parser/transaction_payload.rs:75]: this is more style.... match or use `.ok_or(no_data).and_then(|amount| be_u64(amount).map(...).map_err(...))?`

File: app/rust/src/parser/transaction_payload.rs [hunk 7]
```diff
@@ -64,27 +66,39 @@ impl<'a> StxTokenTransfer<'a> {
...
+        self.0.get(2..22).apdu_unwrap()
     }
 
     pub fn encoded_address(
         &self,
     ) -> Result<arrayvec::ArrayVec<[u8; C32_ENCODED_ADDRS_LENGTH]>, ParserError> {
         // Skips the principal-id at [0] and uses hash_mode and the follow 20-bytes
-        let version = self.0[1];
-        c32::c32_address(version, &self.0[2..22])
+        if let Some(version) = self.0.get(1) {
```
Comment (becominginsane) [inline app/rust/src/parser/transaction_payload.rs:93]: same as above, but here a match is better since it's a bit long

File: app/rust/src/parser/utils.rs [hunk 8]
```diff
@@ -30,3 +30,51 @@ pub fn read_varint(input: &[u8]) -> Result<(&[u8], u64), nom::Err<ParserError>>
...
+}
+
+impl<T, E> ApduPanic for Result<T, E> {
+    type Item = T;
+
+    #[inline]
+    fn apdu_unwrap(self) -> Self::Item {
+        match self {
+            Ok(t) => t,
+            Err(_) => panic!(),
```
Comment (becominginsane) [inline app/rust/src/parser/utils.rs:49]: actually, if you are still tight, it would be _better_ if you replace these with `core::hint::unreachable_unchecked`, that hints the compiler to remove the branch entirely, saving a lot of space, not only due to the removed branch, but the removed panic machinery!

Comment (becominginsane) [reply app/rust/src/parser/utils.rs:49]: https://github.com/Zondax/ledger-rust/blob/feat/v2/bolos/src/panic_traits.rs

**Review by becominginsane — CHANGES_REQUESTED** [review]
Good job! To be fair the biggest improvement I saw on avalanche was removing `rlib` from the crate types, but it seems like it's not used here, so :shrug:...

Anyways, good cleanup!

File: app/rust/src/parser/c32.rs (hunk 1 above)
Comment (neithanmo) [reply app/rust/src/parser/c32.rs:70]: the idea was to remove calls to copy_from_slice for which the compiler would add the panic machinery to handle that case, but after looking at the result from compiler explorer, the copy_from_slice is simpler in terms of amount of instructions.

File: app/rust/src/parser/spending_condition.rs (hunk 4 above)
Comment (neithanmo) [reply app/rust/src/parser/spending_condition.rs:399]: :+1:

Comment (neithanmo) [reply app/rust/src/parser/spending_condition.rs:399]: seems that fill increases by a few bytes, the size of the app each change.

Comment (neithanmo) [reply app/rust/src/parser/spending_condition.rs:399]: it is now 128 bytes bigger after using fill, run multiple times with/without. same result
although it should be depreciable compared to panic as abort.

**Review by ftheirs — APPROVED** [review]

File: app/rust/src/parser/c32.rs [hunk 9]
```diff
@@ -64,55 +66,71 @@ fn double_sha256_checksum(data: &mut [u8; SHA256_LEN]) {
...
-    sha256(&data[..21], &mut output[..]).unwrap();
+    sha256(&data[..21], &mut output[..]).apdu_unwrap();
     data.copy_from_slice(output.as_ref());
     // safe to unwrap as we are passing the right len
-    sha256(&data[..], &mut output).unwrap();
-    data[20..24].copy_from_slice(&output[..4])
+    sha256(&data[..], &mut output).apdu_unwrap();
+    let d = data.get_mut(20..24).apdu_unwrap();
+    let o = output.get(..4).apdu_unwrap();
+    d.iter_mut().zip(o.iter()).for_each(|(d, o)| *d = *o);
```
Comment (becominginsane) [inline app/rust/src/parser/c32.rs:75]: copy from slice missing?

File: app/rust/src/parser/message.rs [hunk 10]
```diff
@@ -118,7 +118,11 @@ impl<'a> ByteString<'a> {
...
+                suffix.iter().zip(m.iter_mut()).for_each(|(s, m)| *m = *s);
```
Comment (becominginsane) [inline app/rust/src/parser/message.rs:122]: still iter_mut?

File: app/rust/src/parser/structured_msg.rs (hunk 5 above)
Comment (becominginsane) [reply app/rust/src/parser/structured_msg.rs:78]: still iter_mut

**Review by becominginsane — CHANGES_REQUESTED** [review]
Not sure if those are better with iter_mut or were forgotten

File: app/rust/src/parser/c32.rs (hunk 9 above)
Comment (neithanmo) [reply app/rust/src/parser/c32.rs:75]: I was getting better results in binary size using them instead of copy_from_slice

File: app/rust/src/parser/message.rs (hunk 10 above)
Comment (neithanmo) [reply app/rust/src/parser/message.rs:122]: well the gain could be not that much if replaced with copy_from_slice comparing with what we could get after using abort as panics. So I will replace them with copy_from_slice.

**Review by becominginsane — APPROVED** [review]

**Comment by ftheirs** [comment]
Closing this https://github.com/Zondax/ledger-stacks/issues/145
